apiVersion: apps/v1
kind: Deployment  
metadata:  
  name: #{the_app}#-#{environment}#-#{slot}#
  namespace: #{namespace}#
  labels:
    shortName: #{the_app}#
    environment: #{environment}#
    app: #{the_app}#-#{environment}#-#{slot}#
    deploymentSlot:  #{slot}#
    buildId: "#{buidId}#"
    dockerImageTag: #{tag}#
#{aadpodidbinding_selector1}#    
spec:  
  replicas: #{replica}#
  selector:
    matchLabels:
      app: #{the_app}#-#{environment}#-#{slot}#
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:  
      labels:  
        shortName: #{the_app}#
        environment: #{environment}#
        app: #{the_app}#-#{environment}#-#{slot}#
        deploymentSlot:  #{slot}#
        buildId: "#{buidId}#"
        dockerImageTag: #{tag}#
#{aadpodidbinding_selector2}# 
    spec:  
      nodeSelector:
         "beta.kubernetes.io/os":  #{osType}#
      containers:  
      - name: #{the_app}#-#{environment}#-#{slot}#
        image: '#{containerRegistery}#/#{image}#:#{tag}#'
        envFrom:
        - configMapRef:
            name: default-config
        ports:   
        - containerPort: 80
        - containerPort: 443
        #readinessProbe:
        #  httpGet:
        #     path: /#{warm_up_path}#
        #     port: #{warm_up_port}#
        #  initialDelaySeconds: 30
        #  periodSeconds: 5
        #  successThreshold: 1
        resources:
          limits:
            cpu: #{cpuLimits}#
            memory: #{memoryLimits}#
          requests:
            cpu: #{cpuRequest}#
            memory: #{memoryRequest}#
#{volumeMounts}#
#{volumes}#
--- 

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: #{the_app}#-#{environment}#-#{slot}#
 namespace: #{namespace}#
 labels:
   shortName: #{the_app}#
   environment: #{environment}#
   app: #{the_app}#-#{environment}#-#{slot}#
   deploymentSlot:  #{slot}#
   buildId: "#{buidId}#"
   dockerImageTag: #{tag}#
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: #{the_app}#-#{environment}#-#{slot}#
 minReplicas: #{minReplicas}#
 maxReplicas: #{maxReplicas}#
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: #{cpuAverageUtilization}#
 - type: Resource
   resource:
     name: memory
     target:
       type: AverageValue
       averageValue: #{memoryAverageValue}#
