apiVersion: v1
kind: Service 
metadata: 
  name: #{the_app}#-#{environment}#-#{slot}#
  namespace: #{environment}#
  labels:
    shortName: #{the_app}#
    environment: #{environment}#
    app: #{the_app}#-#{environment}#-#{slot}#
    deploymentSlot:  #{slot}#
    buildId: #{buidId}#
    dockerImageTag: #{tag}#
        
spec: 
  type: LoadBalancer  #ClusterIP 
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector: 
    app: #{the_app}#-#{environment}#-#{public-slot}#
